### ISSUE TITLE
Criação de Pagina Sobre

### ISSUE THREAD

**Issue by alerossi03** [alerossi02/github-master#3]
Vocês poderiam criar uma página Sobre. Obrigado

**Comment by alerossi02** [comment]
Alterção será realizada

**Comment by alerossi02** [comment]
A página está em produção.

**Comment by alerossi03** [comment]
Obrigado. Estou aguardando.

Em qui., 24 de mar. de 2022 às 10:46, alerossi02 ***@***.***>
escreveu:
